### ISSUE TITLE
Cannot add service reference in Android Studio (Java exception)

### ISSUE THREAD

**Issue by Ravenheart** [ServiceStack/ServiceStack.Java#12]
When adding a ServiceStack Reference in Android Studio it throws an exception IF the service is hosted on a different port other than 80.

java.io.IOException - Failed to read response - http://localhost:9090/

http://localhost/ - OK
http://localhost:9090/ - EXCEPTION

**Comment by Layoric** [comment]
Hi @Ravenheart, having a bit of a problem replicating the issue. Could you confirm which version of Android Studio and ServiceStackIDEA plugin you are running?

Also, could you confirm what version of ServiceStack you are running on the localhost:9090 server and localhost server you are running?

Could you also check the file name and more specifically the file extension what the reference being added? Is it `.java`? Any help to reproduce the problem will help track down the cause. Cheers :+1:

**Comment by Ravenheart** [comment]
Running Android Studio 1.5.1 with the latest (as of around 15.12.2015) ServiceStackIDEA plugin. I am running the latest one from nuget.

**Comment by Layoric** [comment]
Could you check if the extension of the file you are adding is `.java`? If it is other than `.java`, try changing the file extension of the reference file you are adding to `.java` and that should call the correct endpoint to provide Java DTOs.

**Comment by Ravenheart** [comment]
I'll get back to you on monday, but it wouldn't even allow me to create a file if the port is not 80.

**Comment by mythz** [comment]
@Ravenheart cool, if you can send us a screenshot of the dialog that would be great, thx.

**Comment by Ravenheart** [comment]
![servicestack](https://cloud.githubusercontent.com/assets/853378/12019378/2ff2bc46-ad78-11e5-839d-5ff5f19e4e24.png)

**Comment by Layoric** [comment]
@Ravenheart Do you see the Java dtos when you go to `http://localhost:9090/types/java`?

**Comment by Ravenheart** [comment]
Yes I can see them, and they are the same ones that get added to the android studio project when I run the services at port 80.

**Comment by Layoric** [comment]
I am having trouble reproducing the issue on my machines. I create a new ServiceStack project from a template, run it on the default port IIS express/VS gives the project (in this case `http://localhost:15728/`) and I can add the reference without issue.

I've added additional event notifications to see if it might help nail down the issue. If you can, could you update your extension to a nightly build? To do so, you'll need to add our nightly channel plugin repository.

1. Goto File -> Settings -> Plugins
2. Click 'Browse repositories...'
3. Click 'Manage repositories...'
4. Click the green `+` symbol
5. Add the following url as the 'Repository URL' - `https://plugins.jetbrains.com/plugins/nightly/7749`
6. Click OK -> and again for 'Custom Plugin Repositories' dialog.

![image](https://cloud.githubusercontent.com/assets/234642/12044643/3e25abd0-aee9-11e5-91b2-b8021549d831.png)

![image](https://cloud.githubusercontent.com/assets/234642/12044638/29d1ed56-aee9-11e5-841c-cf3ff8aafabc.png)

Search for `ServiceStack` again in the 'Browse Repositories` dialog and you should see an option to update.

When you get the original error in the dialog, your Android Studio Event Log should have more info on the error and hopefully this will help us track it down. Let me know if you have any problems, thanks! :+1:

**Comment by Ravenheart** [comment]
Add ServiceStack Reference failed to read response
        java.io.IOException - Failed to read response - http://localhost:9090/
        Server returned HTTP response code: 503 for URL: http://localhost:9090/types/java/?Package=org.smart_ss.joystick.Core.Service&GlobalNamespace=dtos

**Comment by Ravenheart** [comment]
Here it is, simply run the console project and using Android Studio 1.5.1 try adding the reference.

[AndroidStudioException.zip](https://github.com/ServiceStack/ServiceStack.Java/files/74682/AndroidStudioException.zip)

**Comment by Layoric** [comment]
Hi @Ravenheart, I really appreciated the provided example, however I'm still unable to reproduce the error. Below is a demo gif showing the process working (the renaming of the dto file is only due to Kotlin being used in the Android test project, it should default to `.java` if you aren't using Kotlin).

![working-example-1](https://cloud.githubusercontent.com/assets/234642/12060066/97ae0aee-afbb-11e5-98c2-dd6716aca15f.gif)

I've changed the port to `9099` due to local windows services (TeamCity build agent) already using 9090. I also tested with the same package name `org.smart_ss.joystick` to see if it was the server choking on some of the syntax. But even navigating to `http://localhost:9099/types/java/?Package=org.smart_ss.joystick.Core.Service&GlobalNamespace=dtos` didn't throw the 503 the plugin is reporting. 

I'm assuming the behaviour your seeing is irrespective of what port it's running on? Eg, if you change from `9090` to `12123` you see the same problem? Do you see the same behaviour on your machine if you try the same thing with a new template project? Eg,

1. Open VS
2. File -> New Project -> ServiceStack ASP.NET Empty
3. F5 to run
4. Copy base url
5. Add ServiceStack Reference in Android Studio 

Again, thanks for running through these issues, but really hard to find the issue if we are unable to reproduce the problem. Any other details about your setup (version of Windows, running as admin for self hosted, other situations the problem occurs etc) you can give I'm happy to chase and reflect to try and reproduce the problem.

Cheers! :+1:

**Comment by Ravenheart** [comment]
Well as I'm currently busy with other projects and this one is on the back-burner I will close the issue, being that this is hard to reproduce I'll just leave a note:

if anybody gets this same error just change the port to 80 and it should work.
