### ISSUE TITLE
Naming convention of net.servicestack.client.ResponseStatus class

### ISSUE THREAD

**Issue by KevinPan** [ServiceStack/ServiceStack.Java#22]
The naming convention of the values returned from server is Pascal, but the properties definition of the net.servicestack.client.ResponseStatus is camel. 

For example ResponseStatus.message, the ResponseStatus.message is alway null even if the server side has returned with Message.

**Comment by mythz** [comment]
The [ResponseStatus error is dynamically populated on Exceptions](https://github.com/ServiceStack/ServiceStack.Java/blob/9f644393c66f671f4b9c89c93f84b93815ee81a4/src/AndroidClient/client/src/main/java/net/servicestack/client/JsonServiceClient.java#L212-L219) so it should already be case-insensitive.

Do you have a small-standalone repro/test showing errors not being populated correctly?

**Comment by KevinPan** [comment]
I have created a demo.
DTO:
`[Route("/responsewithmessage")]
public class ResponseWithMessage : IReturn<Response<string>>, IGet {}`

DTO service:

`public object Get(ResponseWithMessage request)
{
    var response = new Response<string>();
    response.ResponseStatus = new ResponseStatus()
    {
        Message = "this is a response with response status message"
    };
    return response;
}`

Here is request and response http package:

> request
GET http://s.hellvip.com/json/reply/ResponseWithMessage HTTP/1.1
Accept: application/json
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; MI 5s MIUI/V8.0.22.0.MAGCNDI)
Host: s.hellvip.com
Connection: Keep-Alive
> 
>response
>Accept-Encoding: gzip
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Vary: Accept
Server: Microsoft-IIS/8.5
X-Powered-By: ServiceStack/4.00 Win32NT/.NET
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: Content-Type
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Tue, 10 Jan 2017 10:54:48 GMT
Content-Length: 80

> {"ResponseStatus":{"Message":"this is a response with response status message"}}

andriod debug screen shot is [here](https://1drv.ms/i/s!AmYbNpD9eFFlgp9Lp-mRoSaymgWWsg)
and andriod demo project is [here](https://1drv.ms/u/s!AmYbNpD9eFFlgp9MiYX7xOND329uAQ)

**Comment by mythz** [comment]
Ok so this isn't from the result of an error, the `ResponseStatus` is only populated by ServiceStack when an error is thrown at which point deserialization is manually parsed to ensure it works in different JS-styles. We can't do this in normal (i.e. non-error) Services as they use the default JSON configuration in the generated DTOs.

You wont be able to reuse `ResponseStatus.Message` since it's a fixed built-in DTO (i.e. schema can't change) and not a DTO that's generated as per your JSON configuration. So if you aren't going to use `JsConfig.EmitCamelCaseNames = true` so the output of your Services match the convention in Java's `ResponseStatus` DTOs then you won't be able to reuse the `ResponseStatus` DTO for non-error responses. In which case you should add a custom `Message` property in your Response DTO and use that instead.
