### ISSUE TITLE
ServiceStack java not working at 5.5

### ISSUE THREAD

**Issue by howsen82** [ServiceStack/ServiceStack.Java#30]
Just had trying to work on the latest ServiceStack 5.5 release, and when try to call the API in Java inside Android studio and Exception throw null values on Exception.getMessage().

If try to use .Net library to work on API services without any issues. The issue with Java try to call client.get() method get null errors instead.
[TestServiceStack.zip](https://github.com/ServiceStack/ServiceStack.Java/files/3190079/TestServiceStack.zip)

**Comment by mythz** [comment]
Since you didn't include a server example I looked at your generated DTO examples to create a matching server:

```csharp
[Route("/hello")]
public class HelloWorld : IReturn<string> { }

[Route("/hello/{Name}")]
public class Hello : IReturn<string>
{
    public string Name { get; set; }
}

public class MyServices : Service
{
    public object Any(Hello request)
    {
        return $"Hello, {request.Name}!";
    }

    public object Any(HelloWorld request)
    {
        return $"Hello, World!";
    }
}
```

The first Exception was [due to a missing network permission](https://stackoverflow.com/a/22395546/85785) which I've added. Next was that you can't use `localhost` inside an Android Mobile App you need to use the [Android IPs which map to localhost on the dev machine](https://developer.android.com/studio/run/emulator-networking).

Once I've made these changes the code works as expected.

![image](https://user-images.githubusercontent.com/89361/57953634-988ce280-78be-11e9-94f2-f10116614738.png)

Can you submit future issues to https://github.com/ServiceStack/Issues - going to close this issue down.
